### ISSUE TITLE
Block Backup&Restore is shown even if include blocks is deselected

### ISSUE THREAD

**Issue by tobiasreischmann** [Opencast-Moodle/moodle-block_opencast#101]
During restore or import of another course, the user gets the option to include opencast videos even if "include blocks" was not checked. In this case, the selection to include opencast videos has no effect. Thus, the option should be either hidden, if blocks were not included or the option should have effect even if blocks were not included.

**Comment by abias** [comment]
Just as a quick note: This issue will be solved by the contribution in #161.
