### ISSUE TITLE
Notification after video has been processed

### ISSUE THREAD

**Issue by t-schroeder** [Opencast-Moodle/moodle-block_opencast#111]
One of our users suggested to add notifications for when a video upload/processing finishes. Moodle's built-in notification system should probably be used for this. It would also be necessary to regularly poll the workflow status for uploaded videos via a cronjob. I'm not sure who should get the notification: only the uploader or each teacher in the course? Either way, I think this would be a good addition to this plugin.
What do you think about a feature like that?

P.S.: Maybe there could also be another type of notification that gets sent when another teacher uploads a video in one of your courses (or when a video is uploaded to the Opencast series, but not through Moodle)?

**Comment by ferishili** [comment]
Hi @TamaraGunkel,
I would like to work on this feature, please assign it to me.
Thanks in advance
