### ISSUE TITLE
No informations for "same file"

### ISSUE THREAD

**Issue by nino2205** [Opencast-Moodle/moodle-block_opencast#121]
If you upload the same file using different filenames or titles, the uploadjob will give the same OC eventid on this job. (because it's the same file hash?)
No processing is done then and no information will be shown in the block.

There should be at least some information for a duplicate event on this video file.

**Comment by tobiasreischmann** [comment]
For this purpose there is the setting:
**Reuse existing uploads**
If activated, multiple videos with the same content hash are uploaded to opencast only once. This saves storage and processing power, but it might cause problems, when you use specific access policies based on opencast series.

It is defaulted to no, which should not result in the case you outlined.
It is a rather legacy setting, which we never used.
Could you check, if you set this setting to yes?

**Comment by nino2205** [comment]
I see, yes, we checked this, i changed it and now everything works fine.

In our case the following happened:
teacher A (Series A): uploaded a file to the block and used it in his course
teacher B (Series B): uploaded the same file to the block and used this video too
teacher A (Series A): missing videofile now

i think it's a problem with our workflow that misses to duplicate the event.
Sorry, and thanks for the fast help.

**Comment by tobiasreischmann** [comment]
If it is really the same file uploaded from two different persons also the setting:
Delete videofile from moodle
might cause the problem. After the first one is uploaded, it could be that the file already gets deleted. But I am not sure.

**Comment by nino2205** [comment]
I think it isn't the Problem of the deleted file. The Video is just moved from series A to series B.
As I see in database, both files are present in the upload table. They have the same filehash and the same eventid. 
With this setting (reuse existing uploads) one teacher is able to move Recordings from one series to another.
I think that's a bug, but it's no longer important to us. We simply deactivate reuse uploads.
