### ISSUE TITLE
Error in backup process

### ISSUE THREAD

**Issue by t-schroeder** [Opencast-Moodle/moodle-block_opencast#123]
See https://github.com/moodleuulm/moodle-theme_boost_campus/issues/84

Through possibly a bug in the boost_campus theme I am able to add the Opencast block to the same course twice. When I do that and there is at least one Opencast video in that course I get the following error when trying to create a course backup:

> Fatal error: Nesting level too deep - recursive dependency? in backup/util/plan/base_plan.class.php on line 68

![image](https://user-images.githubusercontent.com/24255259/78601758-94124500-7855-11ea-9d6d-1e4dfc234f36.png)

This is the line where the error occurs: https://github.com/moodle/moodle/blob/08a62243c5e48721421f3bc67f7411609c7a5cd8/backup/util/plan/base_plan.class.php#L68

Normally this never happens because you normally never have two Opencast blocks in the same course so that line with that comparison operator is never reached. But when it is and there is a video in the course, the comparison somehow causes an endless recursion.

**Comment by abias** [comment]
Hi Tim,

as I just commented on https://github.com/moodleuulm/moodle-theme_boost_campus/issues/84:
I don't have a quick idea why this happens with Boost Campus only and not with Boost.

On the consuming side (i.e. this block), I see that instance_allow_multiple() is set to false which is fine. But I am not sure if this function targets a particular course _page_ or a course as a whole.

My gut feeling is that, if the Opencast block is that sensitive to multiple placements (even if they should not happen), then it should get some extra checks that this really does not happen within a whole course.

**Comment by jonlan** [comment]
I made the same experience in a specific course.

When DEBUG mode is activated and you klick on "Add Video" in the Opencast block the following message appears but instantly disappears.
I somehow managed to catch it:

Error: mdb->get_record() found more than one record!

    line 1636 of /lib/dml/moodle_database.php: call to debugging()
    line 603 of /blocks/opencast/classes/local/upload_helper.php: call to moodle_database->get_record_sql()
    line 41 of /blocks/opencast/addvideo.php: call to block_opencast\local\upload_helper::get_opencast_upload_context()

**Comment by TamaraGunkel** [comment]
Hey,
`course` and `course-editsection` are two different formats where the block can be added.
As I don't see a use case where teachers should need a block on the "edit" pages, I simply removed the permission to add the block there.
