### ISSUE TITLE
Add functionality to copy video to a courses series

### ISSUE THREAD

**Issue by tobiasreischmann** [Opencast-Moodle/moodle-block_opencast#13]
Instead of only allowing to upload a new video, a teacher could be allowed to choose from all videos from other courses and copy single videos to the series of the current course. This way, old videos could be reused. Through copying the videos it is possible to apply different ACLs to the videos and to distinguish them for instance in the annotation tool.

**Comment by ebbertd** [comment]
This could be implemented as a workflow in Opencast so the block would only need to start a workflow. See https://github.com/opencast/opencast/pull/23

**Comment by abias** [comment]
Just as a quick note: This issue will be solved by the contribution in #161.
