### ISSUE TITLE
Increase resilience if Opencast server has problems

### ISSUE THREAD

**Issue by Dagefoerde** [Opencast-Moodle/moodle-block_opencast#133]
The performance of Moodle is compromised when the Opencast server is not reachable.
We are seeing heavily increased page loading times, that are likely due to the fact that the block is sending one or more requests to the Opencast server. If these requests are dropped, Moodle waits until the timeout before proceeding. In the screenshot, the detail page takes 1 minute to load (with no information, because Opencast is down ;) ), and I suspect that there are more than one requests made. This also affects the course pages that contain the block, at least for teachers.

![timeout1min](https://user-images.githubusercontent.com/432117/80460522-3e045f00-8934-11ea-9f6e-00ec16d273e9.png)

So, what I suggest is:
1. Cache heavily, at least for the course page so that that is unaffected -- this could be resolved in #120 
2. Cache even more heavily: If the Opencast server is suspected to be in an error state, cache that in order to avoid more connection attempts! 
3. (maybe) provide an admin switch "Opencast is under maintenance" that a) stops all connection attempts b) provides a message to users in appropriate places
4. Improve the error messages. "Invalid series ID" is not a good error message if, in fact, Moodle did not get a response from Opencast at all -- it should be  "Could not reach server". With the current error message, lecturers are afraid that their videos have been deleted.

**Comment by Dagefoerde** [comment]
Regarding number (2): Do not put this into a shared cache, because this *will* cause race conditions due to the excessive delay, thus affecting our GPFS network storage badly. This can be stored in local cache. As a result,  every webserver will perform (at least) one attempt - that's okay.

**Comment by abias** [comment]
Thank you @Dagefoerde for raising this issue. I agree with everything you have posted and I am looking forward for your solutions :)

Just as two side notes: 
* This issue mainly affects Moodle installations which use the Opencast block as a block on the course page. At Ulm, we don't place the block on the course page, we link to it within the Boost navigation instead - see https://github.com/unirz-tu-ilmenau/moodle-block_opencast#placement. That way, an Opencast downtime or failure does not affect course pages. It only affects the Opencast block overview page which is less bad.
* I am wondering if caching the Opencast backend status in Moodle is really a good idea. As I see in #120, you just invalidate the cache when the user visits the Opencast block overview page. What about any changes which are done directly in the Opencast backend by an authorized Opencast user? As far as I see, these won't be reflected in the Opencast block view until the Moodle user visits the Opencast block overview page again.
An alternative approach to caching could be to fetch the data async with AJAX. That way, the communication between Moodle and Opencast won't block the delivery of the Moodle pages, you can set an appropriate timeout for the AJAX calls and show an descriptive error message in the browser in case the AJAX request times out and returns any error.

**Comment by tobiasreischmann** [comment]
I really like the AJAX idea!

**Comment by tobiasreischmann** [comment]
Also, I agree that the error messages should be improved in case the server is not reachable.
