### ISSUE TITLE
Is the DB table block_opencast_series used at all?

### ISSUE THREAD

**Issue by abias** [Opencast-Moodle/moodle-block_opencast#138]
In our production instance, the DB table block_opencast_series is empty. Course -> Series mappings are stored in tool_opencast_series. Furthermore, I do not see any code snippets which access the block_opencast_series table.

Could we get rid of this table?

**Comment by TamaraGunkel** [comment]
Fixed by f2b3ec43d2ee566062b3d78109b9101e7767525e
