### ISSUE TITLE
Pass return URL to Studio (and maybe not open Studio in a new tab anymore)

### ISSUE THREAD

**Issue by LukasKalbertodt** [Opencast-Moodle/moodle-block_opencast#152]
A couple of weeks ago, I added a feature to Studio that makes it possible to pass a "return URL" to Studio (https://github.com/elan-ev/opencast-studio/pull/674). Studio then renders an additional button "Exit and go back" after up- or downloading the recording. This avoids the user getting trapped in a UI dead end. 

It would be great if this Plugin could support this feature, as I guess it would improve usability. To be honest, I never used Moodle, but quickly searching through the code, it looks like this Plugin simply opens Studio in a new tab (`target="_blank"`) and passes only the `seriesId`. To pass the return URL, you simply add two new GET parameters:

- `return.target`: the URL-encoded URL that the button in Studio links to.
- `return.label`: a short description where the return link leads. This is optional, but can be used to improve the label of the button in Studio. The label is as follows:
  - With `return.label=Moodle`: "Exit and go back to Moodle"
  - Without return label: "Exit and go back to previous page"

Note that the label is slightly different in different languages. If you have information about the user's language, you can of course also pass something like "Moodle course" as label.

Full example (the return URL is a guess, I have no idea how the real URL would look like :smiley:):

```
https://opencast/studio/
   ?upload.seriesId=c6e9b5ab-a9eb-4e6b-9854-01b6886e0587
   &return.label=Moodle
   &return.target=https%3A%2F%2Fmoodle.example.de%2Fplugins%2Fopencast%2F%3Fcourse%3D123
```

This Studio Feature is not included in Opencast 8. However, Studio just ignores unknown GET parameters, so it is safe to unconditionally pass those two GET parameters, regardless of Opencast version.

If there are any questions or suggestions, let me know!

**Comment by ferishili** [comment]
Hi @TamaraGunkel,
is this issue fixed?

**Comment by TamaraGunkel** [comment]
Hey,
I started implementing this but I didn't finished it because of some reasons I don't remember anymore. 
If you want, you can have a look at the commit and finish the implementation.

**Comment by ferishili** [comment]
Of course, please assign it to me. Thanks
