### ISSUE TITLE
Adhoc tasks ar still running even though the duplication workflow is deactivated

### ISSUE THREAD

**Issue by moodlebeuth** [Opencast-Moodle/moodle-block_opencast#159]
Hallo,

if in the administrativ settings of the opencast block under "Settings for backup and restore" the workflow "duplicate LMS Upload from LMS" is disabled and a lecturer is trying nevertheless to import all of the materials from one course into an other and clicked the checkbox for block opencast videos, we found in the logs of moodle cron job the following error messages:

Adhoc task failed: block_opencast\task\process_duplicate_event, An error occured by executing a task for duplication of an event: The plugin block_opencast is not properly configurated. The duplication workflow is missing! Will try to start the workflow again by the next cron job.

This means to us: if the duplication workflow is deactivated, the import job of moodle will still trigger adhoc tasks for the opencast block. Is there a way to prevent this?

Thanks & Greetings,
Michael

**Comment by abias** [comment]
Just as a quick note: This issue will be solved by the contribution in #161.
