### ISSUE TITLE
update on Moodle 3.5

### ISSUE THREAD

**Issue by taraghi** [Opencast-Moodle/moodle-block_opencast#162]
`tool_opencast` provides API functions as well as general settings for the different opencast tools such as `block_opencast`.

Although the `block_opencast` plugin is offered for Moodle 3.5, the `tool_opencast` dependency (v3.9-r1) does not support Moodle 3.5 anymore. This prevents us from updating  `block_opencast` plugin (to v3.9-r2 upwards) on a Moodle v3.5.x setup as these versions depend on `tool_opencast` v3.9-r1

Do you have any solution for this case?

**Comment by NinaHerrmann** [comment]
Hey,
sorry for the confusion, 
tool_opencast should still work on 3.5.
Best regards, 
Nina

**Comment by taraghi** [comment]
Thank you very much
