### ISSUE TITLE
Add default values for metadata fields

### ISSUE THREAD

**Issue by mtneug** [Opencast-Moodle/moodle-block_opencast#163]
Certain metadata fields could receive default values:

* title: name of the file
* licence / rights / etc: default per instructor or course
* ...

**Comment by Zhoha28** [comment]
Has this issue been solved yet? if not can you please assign it to me, I would like to work on this issue

**Comment by NinaHerrmann** [comment]
Hey, any help is appreciated so feel free to take the issue :slightly_smiling_face: :+1:

**Comment by Zhoha28** [comment]
@NinaHerrmann @mtneug I am a little confused as to which files and what are to be updated, can you guys just guide me. I will make the necessary changes, I just need some guidance for the same

**Comment by NinaHerrmann** [comment]
Hey @Zhoha28, I fear we do not have the time to completely guide you through it. Having a default licence per user requires an additional setting for users. I am not completely sure how the second one can be realized. I would guess you can build a Javascript which automatically inserts the name into the field in case it is empty. 
Best regards, 
Nina

**Comment by mtneug** [comment]
It could be sufficient to store the last used value for some of the metadata in a local data store of the browser. I would keep it simple and not change the backend code. Note that metadata fields are configurable so a generic solution would be necessary. Title would be a special case coming from the filename.

**Comment by ferishili** [comment]
Hey @TamaraGunkel, 
what is the current state of this issue? 
Would you please assign it to me, if it is possible?
Thanks in advance

**Comment by TamaraGunkel** [comment]
I think you can just have a look at the metadata fields and check where we already have default values and where not.
I guess you can decide yourself where default values might be helpful but we can discuss them also here if you want.

**Comment by ferishili** [comment]
@TamaraGunkel, I can think of a new db table that can store the latest metadata inputs from the user and use those input values later on as default. What do you think?

**Comment by TamaraGunkel** [comment]
I think saving the defaults per course is a bit overkill, per user should be fine.
So a table with user id and default values should work.
However, I just realized that teachers only see the required fields while the others are hidden. 
I think setting default values for hidden fields is dangerous because they are usually not checked by the teachers.
Thus I think we should only set default values for the required fields.
