### ISSUE TITLE
Export/Import Settings

### ISSUE THREAD

**Issue by TamaraGunkel** [Opencast-Moodle/moodle-block_opencast#168]
The setup of the block can be quite complicated as there are many configurations.
An import/export functionality of the settings would make it easy to provide general configurations to other universities.

**Comment by abias** [comment]
I see the use case behind this issue, but I am wondering if a export / import feature implemented within this plugin is really the best approach. I am especially concerned that a) this export / import feature will have to be maintained alongside with the future development and extension of this plugin and b) some settings of the plugin are depending on the particular Opencast setup (especially workflow settings).

Additionally, there is already a plugin on https://moodle.org/plugins/block_admin_presets which seems to do what you are looking for. Have you tried to export / import the plugin settings with this plugin already? If it works, you might just have to reference this plugin in the documentaiton.

**Comment by TamaraGunkel** [comment]
I definitely see your point regarding a. I have tried the admin presets block but the problem is that we're using external admin setting pages with custom database tables. I guess the best idea is to try migrating the settings to general moodle admin settings (see #149). After that I could try again with the admin block.

As for b, if implementing the functionality itself it would be possible to exclude Opencast specific settings. I'm not sure if that would also be possible with the admin block.

**Comment by TamaraGunkel** [comment]
I looked into the admin block again. Our database tables for the roles and the metadata configurations make it hard to find a good solution. Neither custom database tables nor custom admin settings are supported by the admin presets block.

I basically see three options how to implement this features:
a) Implement our own solution. Disadvantages: we have to maintain this and providing all the features from the admin block (like selecting settings and rolling back imports) is quite much work. Advantage: we don't have to modify the settings.
b) Extend the admin presets block to support external admin settings. Sounds also like much work as I looked into the code and it's quite integrated with the moodle admin configs. Also, we don't know if our PR would be merged.
c) Store the roles and metadata configs (our custom database tables) as Json in the Moodle configs. Disadvantage: Slight overhead because we have to decode/encode the json. We might be limited due to the size but I think that's neglectable as there won't be too many roles/metadata configurations. Advantages: We can fully drop the external settings page and work with moodle configs only. The import/export will work out of the box. Doesn't require too much work as we can keep the existing forms more or less.

I don't think that any approach is perfect. Though I would prefer the third one as it's fast to implement and we can work with moodle settings only. What do you think @abias ?
