### ISSUE TITLE
Mutiple Series per Course

### ISSUE THREAD

**Issue by TamaraGunkel** [Opencast-Moodle/moodle-block_opencast#169]
Currently, the block is bound to a single Opencast series. Supporting multiple series for a block instance would add more flexibility for the teachers.

**Comment by abias** [comment]
I think this issue makes sense, but I see the need for a clear concept and well-defined user stories here.

Currently, the teacher does not have to mind about Opencast series as the series for the course is created and handled on-the-fly and (in most Moodle setups) teachers might not even have the Moodle capabilities to edit the course series within block_opencast.

For our Moodle instance, I see two possible basic user stories:
1. As a teacher, I want to include an existing Opencast series (for example from a previous lecture term) and provide the videos from this series to my students within my Moodle course as well.
2. As an admin, I have a centrally managed lecture capture service which stores videos which are captured by Opencast capture agents into an Opencast series which is separate from the Opencast series which is used within the Moodle courses by block_opencast. It would be nice to provide / show this series within block_opencast to the teacher as well.

**Comment by moodle-mw** [comment]
+1
