### ISSUE TITLE
Add validation for all Configurations

### ISSUE THREAD

**Issue by tobiasreischmann** [Opencast-Moodle/moodle-block_opencast#18]
Especially when series name is empty, Opencast will throw a 500 server error message.
Thus, we should check all configurations for validity.

**Comment by TamaraGunkel** [comment]
Is there anything else that should be validated?
And should the settings also be checked before they are used?

**Comment by synergy-wagner** [comment]
Hi everybody, 

I just wondered whether there is a non moodle standard admin setting page for the block. Is planned validation the reason?

Kind regards
Andi

**Comment by abias** [comment]
I think #80 will solve most of these validation needs, at least if we want to check things like if a field is not empty.
