### ISSUE TITLE
Allow start date to be edited after the video upload

### ISSUE THREAD

**Issue by abias** [Opencast-Moodle/moodle-block_opencast#182]
As a teacher, I am able to set the start date of a video during the initial upload of the video on addvideo.php.
Additionally, when the video is processed and published, I am able to edit the metadata of the video by clicking on the cog icon of the video.

However, I am not able to edit the start date of the video here.
If I picked the wrong date during the initial upload and need to change it, I have to delete the video and upload it again.

**Comment by ferishili** [comment]
Hi @TamaraGunkel,
Would you please assign this issue to me?
Thanks in advance.
