### ISSUE TITLE
Add descriptions to metadata fields

### ISSUE THREAD

**Issue by abias** [Opencast-Moodle/moodle-block_opencast#183]
As an admin, I am able to configure the metadata fields which are provided within the upload videos forms. 
However, these fields currently just have a field name and a field type.
I would appreciate it to also be able to set a field description which is presented either as a help icon near or as a description text below the metadata field within the upload videos form.

The goal of this addition is to be able to provide usage descriptions for the license field or the creator field to the teacher who uploads a video.

**Comment by kaspot** [comment]
Indeed - help icons would be super useful for our users as well.

**Comment by ferishili** [comment]
Hi @TamaraGunkel,
would you please assign this issue to me?
Thanks in advance
