### ISSUE TITLE
Support real autocompletion in the creator and contributor metadata fields

### ISSUE THREAD

**Issue by abias** [Opencast-Moodle/moodle-block_opencast#184]
As a teacher, when I upload a video, I have the possibility to set the creator and contributor metadata fields. These are (by default) provided as autocompletion fields. However, there isn't any autocompletion, I do never get any proposed values. Currently, the autocompletion field type is just (ab)used as a widget to add multiple separated strings.

I would appreciate if the field could either provide some autocompletion like a) the creators and contributors which I have already used for other videos in my course or b) the user fullnames of the teachers in my course or c) the creators and contributors which already exist in the Opencast backend.

If this is not possible or desired, the field type should be changed to something else which does not provoke false expectations.

**Comment by ferishili** [comment]
Hi @TamaraGunkel,
I would like to work on this issue. Could you please assign this issue to me?
Thanks in advance.
