### ISSUE TITLE
Allow to control the visibility of a video during the initial video upload

### ISSUE THREAD

**Issue by abias** [Opencast-Moodle/moodle-block_opencast#187]
As a teacher, I am not able to control the visibility of a video during the initial video upload. I have to wait until the initial video processing is done before I can hide the video if needed. This is especially tricky if I want to upload a video with some assignment solution which should not be public before a defined point in time.

I would appreciate if
a) at least I would be able to set the initial visibility of the video during the initial video upload
b) ideally addittionally a date and time when the video automatically becomes available (which will then require a scheduled task)

**Comment by ferishili** [comment]
Hi @TamaraGunkel,
would you please assign this issue to me?
Thanks in advance
