### ISSUE TITLE
Improve user experience around the video import wizard

### ISSUE THREAD

**Issue by abias** [Opencast-Moodle/moodle-block_opencast#193]
As implemented in #161, the video import wizard lets teachers easily import videos from other courses and especially modify existing LTI modules in the course to point to the imported episode ID afterwards.

However, we have seen things like this happen several times:
* A teacher has a course from the last lecture term where he uploaded many Opencast videos and created Opencast LTI episode modules for these videos.
* A teacher has to fill the course for the next lecture term and simply imports the course content from the old course with the Moodle core course import wizard.
* As the Opencast LTI episode modules are offered within the Moodle core course import wizard, he checks them to be imported and is thinks this is all he needs to do to make the videos avaiable to students again.
* However, as he didn't use the Opencast video import wizard (or does not even know about it) and the videos are not physically in the course's Opencast series, students won't be able to access the videos in the course through LTI. Even worse, due to the way how Opencast LTI works, the teacher _can_ access the videos in the Opencast LTI episodes (as he is a member of the source Moodle course as well) and does not even have a clue why students can't watch the videos in this course.

As we want to avoid teacher frustration and trouble tickets, we think that this user experience should be improved.

Possible solution approaches would be:

1. Semiautomated solutions:
* Add a warning to the Moodle core course import wizard which is shown as soon as Opencast videos (with or without) LTI episodes exist in the course and which tells the teacher that he has to use the Opencast import wizard as well.
* Add a checkbox "Support me to import Opencast videos as well" to the Moodle core course import wizard which redirects to the Opencast import wizard as soon as the Moodle core course import wizard has done his work.
* Show a warning banner on the course main page as soon as orphaned Opencast LTI modules exist in the course and which points the teacher to the Opencast import wizard.
* Show a warning banner on the Opencast overview page as soon as orphaned Opencast LTI modules exist in the course and which points the teacher to the Opencast import wizard.

2. Automated solutions:
* Implement an addition to the Moodle core course import wizard which automagically imports all videos for which Opencast LTI modules are imported and relinks the episode IDs within these modules without asking the teacher anything.

3. Preventing solutions:
* Modify the Moodle core course import wizard in a way that the teacher does not have a possibility to import Opencast LTI modules at all. This way, nothing can go wrong, but the teacher must recreate all modules from scratch in the new course.

4. Informational solutions:
* Modify the Opencast LTI modules in a way that they show a notifications within the description if the video can't be viewed by students of this course.

I am aware that not all approaches can be implemented within block_opencast. Some will require a companion local plugin, some might require core hacks. This is just a brainstorming list.

**Comment by abias** [comment]
To all watchers of this issue:

At Ulm university, we have implemented a solution which 
a) shows a warning banner on the Opencast overview page as soon as broken Opencast LTI modules exist in the course
b) provides an additional wizard to the teacher which helps him to fix (or delete) these broken Opencast LTI modules.

This solution is currently located in https://github.com/moodleuulm/moodle-block_opencast/tree/LMS-5521 and we will test it over the next weeks in production before submitting a PR for it.

It has to be noted that our implementation is based on a upstream version _before_ multiple OC instances and series were possible which means that there will be some rebase effort before our solution could be integrated into the plugin.

**Comment by mwuttke** [comment]
Hello @ferishili, we would prefer the second option suggested by Alex. In other words, as a minimum solution, we could imagine that all videos are imported. As an optional solution, we could also imagine that the user could also select individual videos during the import so that only the videos that are really needed are imported.
