### ISSUE TITLE
Opencast overview page table column are broken when a video is deleted

### ISSUE THREAD

**Issue by abias** [Opencast-Moodle/moodle-block_opencast#198]
When a video is currently deleted, the Opencast overview page table columns are broken as either the visibility or the actions column is missing:

![grafik](https://user-images.githubusercontent.com/1092118/117624931-c3406780-b175-11eb-8eda-201b68102b18.png)

Basically, as soon as a video is deleted, all columns besides the 'status' column should be empty but their `td` tag should still be present in the table.

**Comment by abias** [comment]
Hi @TamaraGunkel ,

thank you for working on this issue.

However, I have to report that the problem still persists (at least for us).
Testing Release v3.11-r1, I still see the same behaviour:
![grafik](https://user-images.githubusercontent.com/1092118/122541737-48972180-d02a-11eb-8a30-87b60b71f4e2.png)

I do not have the time currently to have a deeper look at the code, thus I would like to ask you to re-open the issue and double-check what's missing in your fix if you have more time than I have.

Thanks,
Alex

**Comment by TamaraGunkel** [comment]
Hi, 
the fix is not yet included in the current release (the one you tested).
The issues are closed automatically when merging the feature into the main branch.
However, I'll release a new version next week that just includes bug fixes like this one.

**Comment by abias** [comment]
My bad. I should have looked closer when this patch was integrated. Thank you @TamaraGunkel for clearing this up.

Releasing a new version with this (and other) fixes would be highly appreciated!
