### ISSUE TITLE
Uploadlimit of course and site is not overriden by block

### ISSUE THREAD

**Issue by tobiasreischmann** [Opencast-Moodle/moodle-block_opencast#20]
The problem is that get_user_max_upload_file_size, which is called frequently within the implementation of filemanager, sets the max upload size to the minimum out of php, site, course and module limit. This way the block is not able to override the other limits in the moodle site.

**Comment by tobiasreischmann** [comment]
The branch feature/uploadlimit contains a current implementation of a custom QuickFormElement, which extends the existing filemanager. Unfortunately, we needs to copy lots of code to insert one single line.

**Comment by Dagefoerde** [comment]
Apache seems to hold uploaded files in memory until the upload completes, so at least maintaining that limit may be advisable (and blindly increasing it may not). Therefore it will become necessary to implement our own file manager with support for chunked uploads, each chunk being smaller than the upload limit. It could be based e.g. on http://www.resumablejs.com .

**Comment by tobiasreischmann** [comment]
Or even better. Bring chucked uploads into core!! :)

**Comment by synergy-wagner** [comment]
Hi Tobias, 

You are right, it would need a core change to limit the upload size to specific values, but it is possible to unlimit the upload size in total: 

Our solution:
- created a role with suitable capability and assign this role in context of the block.
- changed the page context of upload form page to the block context to make this work.

Kind regards
Andi

**Comment by do-you-even-curl** [comment]
Our current workaround is adding this `.htaccess` file into the repository directory:
```
<If "%{HTTP_REFERER} == '%{REQUEST_SCHEME}://%{SERVER_NAME}/blocks/opencast/addvideo.php'">
php_value post_max_size 10G
php_value upload_max_filesize 10G
</If>
```
Not 100% secure because people can just send custom HTTP requests with that referrer to upload larger-than-allowed files in other places. But it's just a workaround and this way we don't have to change the core.

**Comment by tobiasreischmann** [comment]
I can see that both of your versions work. 
However, the one of @synergy-wagner does not really scale well, if you have many courses, which use this feature, since you have to set these capabilities for every single block context instance.
The one of @do-you-even-curl completely disables the upload management of moodle, since you have to set the site and the course limit to very high amounts and they are then only restricted by the value in the php.ini .
My version is also not perfect, since a moodle core change is definitely not possible or advisable for  everyone. However, if someone is interested the relevant code is in https://github.com/unirz-tu-ilmenau/moodle-block_opencast/tree/feature/uploadlimit and the necessary code changes are listed above.

In my point of view, the best way would be to integrate a way to allow plugins to exceed the site and course uploadlimits in core. But I can already see that the HQ might not be happy about that.

**Comment by abias** [comment]
As this enhancement can't be implemented without changing Moodle core first and as https://github.com/Opencast-Moodle/moodle-local_chunkupload is now there to solve this issue, I am wondering if we should close this issue with a reference to https://github.com/Opencast-Moodle/moodle-local_chunkupload as the recommended solution.

**Comment by TamaraGunkel** [comment]
Yes, I think we can do that. Chunkupload is well integrated with the block and provides a clean solution.
