### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jonlan** [Opencast-Moodle/moodle-block_opencast#202]
I want to hide the dropdown box "Start Workflow" from teachers. Therefore I uncheck the permisson "block/opencast:startworkflow ".
But the dropdown boy is still visible and clicking it leads to an error message.
Can the dropdown box be made unvisible when "block/opencast:startworkflow " is unchecked?
![image](https://user-images.githubusercontent.com/4759915/120599281-99622400-c447-11eb-8844-98522aeb78b8.png)

**Comment by TamaraGunkel** [comment]
No, not yet. But I agree with you, that this would be useful. I'll implement it in the next release.
