### ISSUE TITLE
Enable admins to copy the content of an existing series

### ISSUE THREAD

**Issue by ebbertd** [Opencast-Moodle/moodle-block_opencast#21]
As an administrator I want to be able to create a new series for a course and select an existing series to copy all or some content from. The user should be able to choose which videos to copy.

Duplicating the event in Opencast could be realised using a workflow, provided that Opencast includes this PR https://github.com/opencast/opencast/pull/23

**Comment by abias** [comment]
Just as a quick note: This issue will be solved by the contribution in #161.
