### ISSUE TITLE
Tasks always stuck on the status "Ready for transfer"

### ISSUE THREAD

**Issue by fishfree** [Opencast-Moodle/moodle-block_opencast#224]
I use crontab to execute Moodle cron job every 15 minutes, but the videos uploaded in the block_opencast always show "Ready for transfer", the schedule task never run as below( algthou I already set the schedule task to */15 every 15 minutes)
![image](https://user-images.githubusercontent.com/1741341/132947445-9716e5df-29ff-4ff5-9afe-e7c924aa8cd7.png)

Only when I manually click the "run now" link in the schedul task list, the video then can be transferred to Opencast.

**Comment by fishfree** [comment]
@TamaraGunkel Could you help me, please? I even set task_scheduled_concurrency_limit to 100 in Moodle, the task is still "Ready for transfer", and in cron logs, there is nothing about Opencast.
![image](https://user-images.githubusercontent.com/1741341/133540283-c05560f4-ee4d-4917-be51-9cf3742d61ce.png)

**Comment by TamaraGunkel** [comment]
Hey,
what exactly do you mean with "there is nothing about Opencast"?
Do you see that the `process_upload_cron` task is executed and there is no log data?
Or is the task not executed at all?

**Comment by fishfree** [comment]
@TamaraGunkel I give it up. Sorry to bother your.
