### ISSUE TITLE
Unlinking series should change ACL

### ISSUE THREAD

**Issue by jojoob** [Opencast-Moodle/moodle-block_opencast#225]
As with the new import series feature (wich works by adding another series to the course and changing ACL on that series and the videos to grant users on the target course the corresponding permissions), the ACL should be changed back when unlinking a series from a course.

I assume a teacher would expect that students can't access the videos of a series after they unlink the series from the course. Currently this is not the case since the ACL is not changed when unlinking a series.

**Comment by ferishili** [comment]
Hey @TamaraGunkel,
would you please assign this issue to me?
Thanks in advance
