### ISSUE TITLE
"A required parameter (ocinstanceid) was missing" by Updating the metadata

### ISSUE THREAD

**Issue by moodle-mw** [Opencast-Moodle/moodle-block_opencast#228]
Hello Tamara,

Wenn I ty to update the metadata of an event, f.i. the titel, I will get the following error message:

A required parameter (ocinstanceid) was missing
More information about this error
Debug info:
Error code: missingparam
Stack trace:
    line 498 of /lib/setuplib.php: moodle_exception thrown
    line 566 of /lib/moodlelib.php: call to print_error()
    line 33 of /blocks/opencast/updatemetadata.php: call to required_param()

We are using Moodle Version 3.10.x, Opencast 10.2 and the block plugins for oc with the last stable release v3.11-r3.

Thanks & Greeting,
Michael

**Comment by moodle-mw** [comment]
@TamaraGunkel: I testet your commit/patch. But with I've got the same error message as before:

`[Fri Oct 01 10:18:23.709629 2021] [proxy_fcgi:error] [pid 21540:tid 140536178448128] [client 172.0.0.1:44276] AH01071: Got error 'PHP message: Default exception handler: A required parameter (ocinstanceid) was missing Debug: \nError code: missingparam\n* line 498 of /lib/setuplib.php: moodle_exception thrown\n* line 566 of /lib/moodlelib.php: call to print_error()\n* line 33 of /blocks/opencast/updatemetadata.php: call to required_param()\n', referer: https://moodle.my-university.de/moodle/blocks/opencast/updatemetadata.php?video_identifier=k22fed49-bc94-4acb-835k-701a1b68e0fa&courseid=106813&ocinstanceid=1
`
Thanks & Greetings,
Michael

**Comment by TamaraGunkel** [comment]
Hey, 
did you also tested it with the master branch?
I’m currently not at work so I can’t test it but I might have missed adding a file to the commit yesterday night when I tried to separate my local changes.

**Comment by moodle-mw** [comment]
@TamaraGunkel: I testet both. The master branch did'nt work, so I testet only [fix](https://github.com/Opencast-Moodle/moodle-block_opencast/commit/5cb12473acd15777d76e2550713d3c22d70f7c27)

**Comment by TamaraGunkel** [comment]
Can you tell me what errors you're getting with the master branch?

**Comment by moodle-mw** [comment]
Sure:
```
Error
Exception - Call to undefined method tool_opencast\local\api::get_instance()
Debug info:
Error code: generalexceptionmessage
Stack trace:

    line 145 of /blocks/opencast/classes/local/apibridge.php: Error thrown
    line 86 of /blocks/opencast/block_opencast.php: call to block_opencast\local\apibridge->get_block_videos()
    line 341 of /blocks/moodleblock.class.php: call to block_opencast->get_content()
    line 235 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
    line 1181 of /lib/blocklib.php: call to block_base->get_content_for_output()
    line 1239 of /lib/blocklib.php: call to block_manager->create_block_contents()
    line 374 of /lib/blocklib.php: call to block_manager->ensure_content_created()
    line 3950 of /lib/outputrenderers.php: call to block_manager->region_has_content()
    line 50 of /theme/boost_campus/layout/columns2.php: call to core_renderer->blocks()
    line 1374 of /lib/outputrenderers.php: call to include()
    line 1304 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
    line 288 of /course/view.php: call to core_renderer->header()
```
Thanks,
Michael

**Comment by TamaraGunkel** [comment]
Ah okay, I see. I didn't increased the dependency version numbers yet. You also need the master branch of the tool

**Comment by moodle-mw** [comment]
Oh, sorry. Now, with the latest version of the master branch of the admin tool it works again.

Thanks & Greetings,
Michael
