### ISSUE TITLE
Job failed due to: core\invalid_persistent_exception: error/invalidpersistenterror

### ISSUE THREAD

**Issue by fishfree** [Opencast-Moodle/moodle-block_opencast#229]
In my second Moodle course, I created an Opencast block, uplaod a video. Then it always shows as below:
![image](https://user-images.githubusercontent.com/1741341/136499433-a9762d33-bed3-4940-964a-9bed7008f19a.png)
In the Opencast console, it shows up many series with same name but different uuid as below:
![image](https://user-images.githubusercontent.com/1741341/136499518-cd5a5f95-00ca-4a83-bc31-1f40e5417a47.png)

Then in the Moodle /admin/tasklogs.php page, click the log viewer icon as below:
![image](https://user-images.githubusercontent.com/1741341/136499595-bc335ee1-4112-453c-96b8-9b58c62c84ae.png)

It showed up as below:
```
Execute scheduled task: Process upload (block_opencast\task\process_upload_cron)
... started 12:20:01. Current memory use 13.4MB.
proceed: 10
Job failed due to: core\invalid_persistent_exception: error/invalidpersistenterror in /home/www/moodle/moodle/lib/classes/persistent.php:467
Stack trace:
#0 /home/www/moodle/moodle/blocks/opencast/classes/local/apibridge.php(627): core\persistent->create()
#1 /home/www/moodle/moodle/blocks/opencast/classes/local/apibridge.php(648): block_opencast\local\apibridge->create_course_series()
#2 /home/www/moodle/moodle/blocks/opencast/classes/local/upload_helper.php(467): block_opencast\local\apibridge->ensure_course_series_exists()
#3 /home/www/moodle/moodle/blocks/opencast/classes/local/upload_helper.php(606): block_opencast\local\upload_helper->process_upload_job()
#4 /home/www/moodle/moodle/blocks/opencast/classes/task/process_upload_cron.php(37): block_opencast\local\upload_helper->cron()
#5 /home/www/moodle/moodle/lib/cronlib.php(253): block_opencast\task\process_upload_cron->execute()
#6 /home/www/moodle/moodle/admin/cli/scheduled_task.php(167): cron_run_inner_scheduled_task()
#7 {main}
... used 17 dbqueries
... used 0.64898300170898 seconds
Scheduled task complete: Process upload (block_opencast\task\process_upload_cron)
```

What's wrong? I strictly followed the instructions here, and the videos uploaded in the first-tried Moodle course worked normally.

I turned on debugging mode on both Moodle and Opencast, but no relevant logs found.

**Comment by TamaraGunkel** [comment]
Hey,
which plugin version do you use?

**Comment by fishfree** [comment]
@TamaraGunkel Sorry for reply so late. After upgrading to the latest version, the problem seems disappeared. Thank you very much!
