### ISSUE TITLE
Content of subject field is cut off when uploading via "Add video" page

### ISSUE THREAD

**Issue by scharnkn** [Opencast-Moodle/moodle-block_opencast#231]
When uploading a video via the "add video" page, the content of the 'subject' field is cut off after 50 characters. This does not happen when uploading e.g. via the Opencast Admin UI.
Please note, that the value is displayed correctly at first, but cut off as soon as the actual workflow starts.

**Comment by TamaraGunkel** [comment]
Hey,
the plugin does not truncate the subject. Could that be a configuration problem with the Opencast External API?

**Comment by scharnkn** [comment]
Hi,

I forgot to mention in my first post, the same happens, when creating a series via the opencast block.

I took a look at the network traffic when creating a series and it seems the value is already cut off when it reaches Opencast, so something must be happening on the Moodle side. 

The relevant part of the POST request to the `/api/series` endpoint is looks like this:

```
Content-Disposition: form-data; name="metadata"

[
  {
    "label": "Opencast Series Dublincore",
    "flavor": "dublincore\\/series",
    "fields": [
      {
        "id": "title",
        "value": "3288 - Moobleblock Test"
      },
      {
        "id": "subject",
        "value": "11111111112222222222333333333344444444445555555555"
      },
      {
        "id": "description",
        "value": "111111111122222222223333333333444444444455555555556666666666777777777788888888889999999999"
      },
      {
        "id": "language",
        "value": ""
      },
      {
        "id": "rightsHolder",
        "value": "test"
      },
      {
        "id": "license",
        "value": "CC0"
      },
      {
        "id": "creator",
        "value": [
          "test"
        ]
      },
      {
        "id": "contributor",
        "value": [
          "test"
        ]
      }
    ]
  }
]
```

On the Moodle side I used the same values for "subject" and "description", but only "subject" is cut off.

Could this be some Moodle core functionality getting the way?

**Comment by TamaraGunkel** [comment]
Hey,
you're right. We're using the autocomplete element for the `subject` field (because OC videos can have multiple subjects). 
The autocomplete element processes input as type `PARAM_TAG` which is truncated after 50 chars. 
The description field is a text field where this doesn't happen.

Here the max length constant is defined: 
https://github.com/moodle/moodle/blob/master/lib/moodlelib.php#L389

There doesn't seem to be a way to change this value for a single form element. I don't really have an idea how to solve this. For most users, 50 chars are enough. Maybe you could simply increase the global tag limit?

**Comment by scharnkn** [comment]
Hi Tamara,

I think I found a workaround, I changed the field type of the "subject" metadata from "autocomplete" to "text" and now the whole string is transferred.

> OC videos can have multiple subjects

Maybe I misunderstand, but to me in seems like in the Admin UI, it's just one string. I cannot add multiple values to the subject field (like e.g. for presenters).

**Comment by TamaraGunkel** [comment]
Hey,
okay great. Opencast subjects are somewhat inconsistent. The API endpoint expects and returns an array but in the admin UI these subjects are displayed as comma separated values.
