### ISSUE TITLE
"ocinstanceid" error – group visibility

### ISSUE THREAD

**Issue by llttugraz** [Opencast-Moodle/moodle-block_opencast#233]
The following error appears in courses with videos restricted to course-groups:

`Coding error detected, it must be fixed by a programmer: Unexpected property 'ocinstanceid' requested.`

![image](https://user-images.githubusercontent.com/28404082/139278182-bbabe5be-4f53-44f4-a0a9-ad200392fc2d.png)

We are not able to reproduce the above case – possibly because it concerns courses and videos that were set up before the last plugin update.

Newly set up videos show the following:
Steps to reproduce (the visibility feature should be activated in the general plugin settings; also the possibility to restrict videos to course groups):

* in a moodle course with Opencast Videos block and available videos, add a course group
* set the visibility to for one of the videos to the course group

<img width="1894" alt="image" src="https://user-images.githubusercontent.com/28404082/139279880-643566d8-bdf2-4157-82cb-30b376ef3d6b.png">
<img width="1884" alt="image" src="https://user-images.githubusercontent.com/28404082/139280031-efa5ea84-be36-49fd-9ead-6cfc8ca0a04b.png">

As seen in the last screenshot, visibility shows an error "!"
Mouse hover text:
"The visibility of the video is in an invalid status. Click to choose the correct visibility."

In Opencast a regular group role is set e.g. G123_Learner (so nothing out of the ordinary there).

**Comment by TamaraGunkel** [comment]
Hey, 
thanks for the detailed information. I was also not able to reproduce the error. But I fixed the issue with the invalid status.
