### ISSUE TITLE
Title is not linked on Overview-Page

### ISSUE THREAD

**Issue by tjettmers** [Opencast-Moodle/moodle-block_opencast#239]
In blocks/opencast/index.php?courseid=x&ocinstanceid=y there is a table with a column "title". i would be useful to put a link to this title, leading to the respective video.
![image](https://user-images.githubusercontent.com/60962776/144419030-f0227627-1553-4082-8b57-80fafa0bdd21.png)

**Comment by ferishili** [comment]
Hi,
Please take a look at https://github.com/Opencast-Moodle/moodle-block_opencast/issues/58
As well as this PR: https://github.com/Opencast-Moodle/moodle-block_opencast/pull/240
It might fullfil this issue as well!
Cheers

**Comment by TamaraGunkel** [comment]
I forgot to reference this issue in my commit but this is fixed in the newest release v3.11-r7.
