### ISSUE TITLE
 Choose visibility in resource upload form

### ISSUE THREAD

**Issue by colradectug** [Opencast-Moodle/moodle-block_opencast#244]
When uploading resources, the visibility of those are automatically set to visible. A checkbox for choosing the visibility of the resource manually before uploading would be helpful for many users. This checkboxes (advcheckbox) default value could be set with admin_settings to be either default_visible or default_hidden.

**Comment by TamaraGunkel** [comment]
Hey,
this feature is already listed in Issue #187 and will soon be realized by PR #248.
