### ISSUE TITLE
enhance series import 

### ISSUE THREAD

**Issue by fsufrre** [Opencast-Moodle/moodle-block_opencast#252]
some teachers asked for the "old" feature to pick single videos while import videos from other courses. since we changed from "duplicate workflow" to "ACL change" this is not possible anymore.

For that case I would be nice to differentiate  between "import whole series" or "pick certain videos" when importing videos from another series.
so either the series acl are altered or duplicate workflow of opencast is used.

**Comment by ferishili** [comment]
Hi @fsufrre,
I am going to fix this issue, however, I would need more details about this and if there would be mockups, examples etc. would be much nicer!
I am looking forward to your quick answer here, since we are reaching the deadline for refactoring-lock!
Thanks

**Comment by fsufrre** [comment]
Hi @ferishili,

this issue just faces the problem that you can't select single videos during the import wizard.
If you want to use just one video from another course you have to import the whole series.

![grafik](https://github.com/user-attachments/assets/1da2f9a4-3e82-4454-bf35-c9b1507ea1bb)

**Comment by ferishili** [comment]
Hi @fsufrre,
thanks for your input. Just one more question, are we talking about selective videos during import when the import mode is set to "ACL change"?
If that is the case, I would say, it is technically not possible or better put: not feasible for the following reasons:
- When changing acl of videos, we are bound to (or at leaset I understood it this way) also change series acl. This will result in unwanted access later.
- Even if it possible to pick one video and change its acl, it would be almost impossible to keep track of which video is related to what course based on acls. So the problem arises when one deletes a course, then those single videos acls would not get updated and we will end up having a long list of unwanted acls in videos!

Please correct me if I am wrong and give me your ideas / discuss this if you think otherwise.

**Comment by fsufrre** [comment]
HI @ferishili I understand, but what would you suggest for this use case:

- teacher has a course "A" with 100 videos
- teacher has a second course "B" and wants to use 2 videos from course "A"

At the moment you can set a global parameter: "Duplicate" or "ACL change".

Option 1: If we choose "Duplicate" the teacher is able to select just those two single videos. Fine for him, not really fine for us because we have a physical second file on at the system and wasting storage.

Option 2: If we choose "ACL change" all videos will be selected and imported. But it's quite confusing for the teacher to scroll through all 100 videos to select those he wants.

I'm fine with option 2. As you mentioned, it provides a better handling when you delete courses/series. But usability for this case is not nice. Also it leads to longer loading times when you open the block overview.
I just was curious if there is a way improving the process.

**Comment by ferishili** [comment]
Hi @fsufrre,
thanks for your explanation, I am totally aware of this situation.
I think (if I am not mistaken) for this use case at the time of implementing "ACL Change" mode, we decided that the teacher in this case should ignore that course-level import and perform the manual video import offered within the opencast video block. But I would guess, it is a bit unpleasant for them to go through the video import one more time!

I did a little research and finding on this. And I came across the idea of introducing a new table to also map the course-events, but I wasn't able to expand the idea and think of the pros and cons in a long run. I would be happy to hear your opinion on this.
This idea should make it possible to tackle the management/handling problem!

**Comment by ferishili** [comment]
Hi,
after discussing this feature request, here is the final decision:

> Wir haben diesen Wunsch diskutiert, haben aber gesehen, dass die Implementierung dieses Features die Import-Möglichkeiten erstmal noch komplexer machen würde. Wir würden das Issue erstmal nicht implementieren und die Import-Möglichkeiten im Rahmen des Refactorings erstmal genau frisch konzeptionieren.

**Comment by fsufrre** [comment]
sorry for the late reply, github still sends to my old mail address.

Thanks for discussing. in this case i would close the issue.
