### ISSUE TITLE
Recording Video Issue in Moodle integration with Opencast

### ISSUE THREAD

**Issue by thetmar999** [Opencast-Moodle/moodle-block_opencast#253]
Hello, Good day to you all

I would like to get your help with the issue regarding using Opencast in Moodle. 
I want to record the videos in the Opencast server that pass through the Moodle with single sign on.

I had the integration of Moodle3.11 with the Opencast9.80 CentOs server. Although the Opencast web site is ssl domain name, Moodle web site is used with IP address till now.

https://moodle.org/plugins/tool_opencast
https://moodle.org/plugins/block_opencast
https://moodle.org/plugins/mod_opencast
https://moodle.org/plugins/repository_opencast
https://github.com/Opencast-Moodle/moodle-filter_opencast
https://moodle.org/plugins/local_chunkupload
https://moodle.org/plugins/local_boostnavigation

I downloaded and installed the latest version of above 7 plugins in Moodle. And then I set up some configuration steps in Moodle.
 
 For integration of Moodle with opencast studio in opencast server, I set up  the opencast-url as domain name, key and secret in Moodle and put some configuration  in Opencast Server.
 
 After that when I chose the opencast video tab in the course and clicked the  button(record video) in Moodle,  I got the error page. Pls kindly see the figures.
 
I tried my best to solve this problem, but I haven't fixed it now. I would like to know the ways and get suggestions from you that the Moodle users can record the video in opencast with single sign on. I would appreciate it if you could help us solve this problem.

[
![1](https://user-images.githubusercontent.com/98933010/152278977-60fa99b6-aab7-4e1c-9f8a-8b07230e0e27.jpg)
![2](https://user-images.githubusercontent.com/98933010/152278986-806e3edc-ff7b-4fa1-af55-188f9fee0273.jpg)
![3](https://user-images.githubusercontent.com/98933010/152278992-7451d00d-4367-48f3-a547-6ba683a52539.jpg)
![4](https://user-images.githubusercontent.com/98933010/152278995-0bfe202f-4157-4412-bd99-0c46aaf6689f.jpg)
![5](https://user-images.githubusercontent.com/98933010/152278998-b5421c0d-e776-49c3-942b-57d43ddc0b68.jpg)

](url)

**Comment by ferishili** [comment]
Hi @thetmar999
The lti problem would be solved in the next release and this issue is a duplicate! Please refer to this PR #281 
I am closing this issue in favor of the above PR!
