### ISSUE TITLE
"Change owner" workflow is visible although "ACL owner role" setting is empty

### ISSUE THREAD

**Issue by scharnkn** [Opencast-Moodle/moodle-block_opencast#260]
The description of the `ACL owner role` key in the plugin settings says that 
> If empty, owner-related plugin functionalities are disabled.

However, in the video overview screen the "Change owner" workflow is visible even when the setting is empty:

![image](https://user-images.githubusercontent.com/44021701/153879687-8395c180-ecc5-4576-a622-44ebb0cc48c0.png)

We are using version 3.11-r7 of the plugin.

**Comment by mwuttke** [comment]
I can repreduce this error.
