### ISSUE TITLE
How to pass parameters to Opencast Workflow Operation Handler?

### ISSUE THREAD

**Issue by fishfree** [Opencast-Moodle/moodle-block_opencast#270]
I'd like to pass a language string parameter to the Opencast IBM Watson or Google Cloud Speech API workflow operation handler. How to make that. I can add arbitrary Event metadata on the page admin/settings.php?section=block_opencast_generalsettings_1 , which, however, seems impossible to pass to the worflow operation handler[ which can be passed by Configuration Panel](https://zivgitlab.uni-muenster.de/zhldigital/electures/opencast/opencast/blob/e4cad9cf36230a4639ce23bf20c30cb82bddaa75/docs/guides/admin/docs/configuration/workflow.md#accept-user-input).

**Comment by ferishili** [comment]
To do this you need to use start workflow feature, by selecting any workflow that has config panel you would then be able to pass the params.
I close this issue because it is a question which is answered! :)
