### ISSUE TITLE
Error: Invalid current value: schedule-and-upload after upgrading to the latest released version of block_opencast

### ISSUE THREAD

**Issue by fishfree** [Opencast-Moodle/moodle-block_opencast#271]
My Moodle version: 3.10, Opencast version 10.20
After upgrading to the latest released version of block_opencast, when access  /blocks/opencast/addvideo.php?courseid=11049&ocinstanceid=1, it shows errors as below:
![image](https://user-images.githubusercontent.com/1741341/161747526-7daca6e9-9122-4dff-866c-ae3510181039.png)

When access  /admin/settings.php?section=block_opencast_generalsettings_1, it shows errors as below:
![image](https://user-images.githubusercontent.com/1741341/161745223-6a0e026e-d130-4f58-a088-e8b74c2dbfa6.png)

But no option to select. The same errors are also as these:
![image](https://user-images.githubusercontent.com/1741341/161745604-378f1a2f-e901-46a0-a8c0-44a908d678ac.png)
![image](https://user-images.githubusercontent.com/1741341/161745637-029bcecd-28d4-49ba-93e9-b8d09d6d900b.png)

**Comment by ferishili** [comment]
Hi @fishfree,
I hope that the issue has been resolved by now. I have tried to reproduce this issue, and I found out that, upgrading to newer version with one release at a time (step by step) has no issue and the problem you have dealt with does not arise.
With that said, I came to a conclusion that, you have tried to upgrade from a version which was before the break-change (multiple-instancing) to a version that is considered after that break-change. In this case, the false data and configs issue may occur.

I am closing this issue, as it is not reproducable and is irrelavant anymore.
