### ISSUE TITLE
Bug: LTI for launching OC Studio assumes there is a `lticonsumerkey_` + index setting

### ISSUE THREAD

**Issue by mtneug** [Opencast-Moodle/moodle-block_opencast#272]
Legacy? configurations might still use `lticonsumerkey` instead `lticonsumerkey_1`? At least our Moodle instance had no values for `lticonsumerkey_1` for the default instance of Opencast.

**Comment by ferishili** [comment]
Please refer to #281

**Comment by ferishili** [comment]
completed in #281
