### ISSUE TITLE
workflow_tag works only with one single entry

### ISSUE THREAD

**Issue by mwuttke** [Opencast-Moodle/moodle-block_opencast#274]
I tried to set in the moodle Admin-UI for the opencast block two workflow tags, one for an amberscript workfkow for the english  (_amberscript-moodle-eng_) transcription and one amberscript workflow for the german transcription (_amberscript-moodle_), once comma and once semicolon separated. But unfortunately, it works only with one single entry! Neither comma nor semicolon is supported.

Is there any solution?

Thanks,
Michael

**Comment by ferishili** [comment]
Hi @TamaraGunkel 
Could you please assign this issue to me. Thanks in advance.
