### ISSUE TITLE
Opencast Studio recordings are not assignd to the series

### ISSUE THREAD

**Issue by mwuttke** [Opencast-Moodle/moodle-block_opencast#275]
Opencast Studio can be started and used from the Opencast block as usual. The recordings are also created without errors, transferred to Opencast and processed. But the assignment to the Opencast series of the Moodle course from which the recording was created is not done. Is this error related to the change/move of the LTI settings from the block to the tool plugin?

System used:
Opencast version: 10.11
Moodle version: 3.10
Moodle plugins version: block: v3.11-r8 or -9 & tool: v3.11-r8
OS: Linux Mint
Browser: latest version of Chromium & Firefox

Thanks & Greetings,
Michael

**Comment by ferishili** [comment]
Hi @TamaraGunkel,
Could you please assign this issue to me as well.
Thanks in advance
