### ISSUE TITLE
"Record video" button not linked to go via LTI although LTI credentials are provided

### ISSUE THREAD

**Issue by taraghi** [Opencast-Moodle/moodle-block_opencast#287]
### Steps to reproduce:

**Plugin installed**: 
- block_opencast: v3.11-r9
- tool_opencast: v3.11-r8

**Settings tool_opencast**:
- `ocinstances` : `[{"id":1,"name":"Default","isvisible":true,"isdefault":true}]`
- configuration: alle fields are filled out including `lticonsumerkey` and `lticonsumersecret`

**Relevant settings block_opencast (Opencast Studio Integration)**:
- `enable_opencast_studio_link_1`: YES
- `open_studio_in_new_tab_1`: YES
- `opencast_studio_baseurl_1`: EMPTY
- `show_opencast_studio_return_btn_1`: NO
- `opencast_studio_return_btn_label_1`: EMPTY
- `opencast_studio_return_url_1`:  `/blocks/opencast/index.php?courseid=[COURSEID]&ocinstanceid=[OCINSTANCEID]`

Clicking on the button "Recode video" in the block, redirects the user to `OPENCAST_ENDPOINT . '/studio?upload.seriesId=SERIES_ID` although the credentials for LTI in `tool_opencast` are given

### The current bug behavior:

The button "Record video" link is set to `OPENCAST_ENDPOINT . '/studio?upload.seriesId=[SERIES_ID]`

### Expected correct behavior

The button "Record video" link should be: `MOODLE_WWWROOT` . '/blocks/opencast/recordvideo.php?courseid=[COURSEID]&ocinstanceid=1`

### Possible fixes:

In `/blocks/opencast/renderer.php`, function `render_block_content()` on line 487 the LTI Consumer Key is read from the config setting `tool_opencast/lticonsumerkey_1` as follows:
```
get_config('tool_opencast', 'lticonsumerkey_' . $ocinstance->id)
```

In` /admin/tool/opencast/settings.php` lines 86 - 126, the settings are defined without the suffix `_[ocinstanceid]` for the case the  oc instance is a default one as follows:
```
if ($instance->isdefault) {
...
                $lticonsumerkeysetting = new admin_setting_configtext('tool_opencast/lticonsumerkey',
                    get_string('lticonsumerkey', 'tool_opencast'),
                    get_string('lticonsumerkey_desc', 'tool_opencast'), "");
                $settings->add($lticonsumerkeysetting);
...
} else {
...
                $lticonsumerkeysetting = new admin_setting_configtext('tool_opencast/lticonsumerkey_' . $instance->id,
                    get_string('lticonsumerkey', 'tool_opencast'),
                    get_string('lticonsumerkey_desc', 'tool_opencast'), "");
                $settings->add($lticonsumerkeysetting);
...
}
```

Consequently for the setup where only one oc instance is configured and that is set as default, the LTI consumer key is saved under `tool_opencast/lticonsumerkey`, but the block_opencast tries to read the value from `tool_opencast/lticonsumerkey_1` which does not exists (false). Therefore block_opencast concludes that no LTI consumer key is set. This results in the incorrect link.

Even though if one manually calls the expected url `MOODLE_WWWROOT . /blocks/opencast/recordvideo.php?courseid=[COURSEID]&ocinstanceid=1` in the browser, opencast shows the error message that no LTI key could be found. Because in `/blocks/opencast/recordvideo.php` on lines 121, 122 the `key` and `secret` are read from `lticonsumerkey_1` and `lticonsumersecret_1` correspondingly which appear to be empty in the case of the setup described above.

**Comment by ferishili** [comment]
Please see #281, this PR fixes LTI auth problems and enhances the "Record Video"!
