### ISSUE TITLE
Find unpublished videos (crossed out eye)

### ISSUE THREAD

**Issue by BerengarWLehr** [Opencast-Moodle/moodle-block_opencast#299]
Is there some way to find all unpublished videos in the moodle database? I can not find the right table/column/query to find thouse.

**Comment by ferishili** [comment]
Hi @BerengarWLehr,
Unfotunately, that is something that depends not only on moodle but also on opencast ACL data as well. I would then recommend that you ask this question in the community chat if it is still an issue for.
I close this issue as it is a question answered!
