### ISSUE TITLE
Hardcoded role name

### ISSUE THREAD

**Issue by t-schroeder** [Opencast-Moodle/moodle-block_opencast#302]
For the "Presenter(s)" and "Contributor(s)" autocomplete fields we get the users in the current course that have the role with shortname "editingteacher": https://github.com/Opencast-Moodle/moodle-block_opencast/blob/653e01ea8e774c695c65b2234fa55ba926f81e0c/classes/local/autocomplete_suggestion_helper.php#L64-L71
In our Moodle instance there is no role with that name. So this always creates a warning in the following lines when trying to access `$role->id` since `$role` is `false`: https://github.com/Opencast-Moodle/moodle-block_opencast/blob/653e01ea8e774c695c65b2234fa55ba926f81e0c/classes/local/autocomplete_suggestion_helper.php#L71-L75

In my opinion there should be no hardcoded role. It should either be an admin setting where you select a role (or multiple roles) or it should be done through a capability.

**Comment by ferishili** [comment]
Merged and completed in Merged in [b2f7559aaef5752889872a8e2b4569b04fda675d](https://github.com/Opencast-Moodle/moodle-block_opencast/commit/b2f7559aaef5752889872a8e2b4569b04fda675d)
