### ISSUE TITLE
Browser warning about leaving page after creating/editing series

### ISSUE THREAD

**Issue by scharnkn** [Opencast-Moodle/moodle-block_opencast#307]
Steps to reproduce:
- Go to the "Manage series" screen
- Create a new series or edit a series' metadata
- Attempt to leave the page

Result: 
There is a warning about leaving the page and potentially losing unsaved data. 
After leaving the page and re-entering it, the changes are still there, so no data is lost. However, this warning is potentially confusing for users.

![image](https://user-images.githubusercontent.com/44021701/197529712-5c77531b-907c-4920-a681-1de8cf3f6e96.png)

This happens both with Firefox and Chromium (Linux).

**Comment by ferishili** [comment]
Hi, to my knowledge it is a feature in Moodle itself and has nothing to do with this plugin! Not sure but I hope there is some setting to configure this feature!

**Comment by ferishili** [comment]
Closing this issue, because it is irrelevant
