### ISSUE TITLE
Videos cannot be uploaded with the Opencast Block Plugin to Opencast 13.2+

### ISSUE THREAD

**Issue by MatthiasKollenbroichWWU** [Opencast-Moodle/moodle-block_opencast#318]
Uploading videos with the _Opencast Block Plugin_ fails, if _Opencast 13.2+_ is used. The upload still worked for *Opencast 13.1-2*.

Maybe the problem is related to the following since _Opencast 13.2_ fixed issue: https://github.com/opencast/opencast/pull/4628

Opencast release notes: https://docs.opencast.org/r/13.x/admin/#releasenotes/

**Comment by ferishili** [comment]
Hi, this issue is not related to the plugin, therefore, it is flagged as invalid for now
