### ISSUE TITLE
Moodle Opencast ingest upload fails with PHP 8.0 when using ingest upload

### ISSUE THREAD

**Issue by slaudel** [Opencast-Moodle/moodle-block_opencast#319]
After switching from PHP 7.4 to PHP 8.0 uploads from Moodle to Opencast fail if "Ingest upload" is selected.
In file [/classes/local/ingest_uploader.php](https://github.com/Opencast-Moodle/moodle-block_opencast/blob/master/classes/local/ingest_uploader.php) 

`
if (version_compare(phpversion(), '8', '>=')) {
      $file = new \CURLStringFile($episodexml, 'dublincore-episode.xml', 'text/xml');
  } else {
      $file = new PolyfillCURLStringFile($episodexml, 'dublincore-episode.xml', 'text/xml');
  }
`

But [PHP documentation](https://www.php.net/manual/en/class.curlstringfile.php) tells class curlstringfile is available from PHP 8.1:
> (PHP 8 >= 8.1.0)

So the check for PHP 8 should be a check for PHP >= 8.1.

**Comment by slaudel** [comment]
Maybe this is related to [https://github.com/Opencast-Moodle/moodle-tool_opencast/issues/44](https://github.com/Opencast-Moodle/moodle-tool_opencast/issues/44)?

**Comment by ferishili** [comment]
This issue is fix by opencast php library integration in https://github.com/Opencast-Moodle/moodle-block_opencast/commit/f1e8538e44035110d16379dc66ce5636227e6aa4
