### ISSUE TITLE
missing string identifier

### ISSUE THREAD

**Issue by ekreim** [Opencast-Moodle/moodle-block_opencast#336]
Hello,

it is just a small issue:
the string identifier for opencast:canchangeownerforallvideos is missing in lang/en/blocks_opencast.php of release v4.0-r1

Maybe you can add it in a future release. Thanks!

Elke

**Comment by ferishili** [comment]
Added into master via https://github.com/Opencast-Moodle/moodle-block_opencast/commit/6bec3d8636fd06c53a0fa1acab851d9d3a585e21
Added into Release_v4.1 via https://github.com/Opencast-Moodle/moodle-block_opencast/commit/dab1173111fd323d265e5c2c99f12dbd204dc799

Close as completed
