### ISSUE TITLE
After deleting and re-adding an Opencast block, there are two Opwencast series with the same name

### ISSUE THREAD

**Issue by mwuttke** [Opencast-Moodle/moodle-block_opencast#351]
**Actual behavior**
If you "hide" an Opencast block in Moodle, i.e. remove it from the course page, and then add it again, all the videos in the block suddenly "disappear". However, they are only not visible in the newly added block and are therefore no longer available to the teacher. However, they are not deleted in Opencast and still belong to the Opencast series of the Moodle course. When the Opencast block is re-added to the same course, a new series is created in Opencast with a new series ID. There are then two Opencast series that belong to the same Moodle course. They both have the same name _Course_Series_{Moodle-courseID}_. However, one has the addition __(ID:seriesID)_.

**Expected behavior**
If an Opencast block is accidentally or deliberately deleted and later re-added to the same Moodle course, the videos belonging to the Moodle course should also reappear in the Opencast block. This means that no new series should be created in Opencast. Instead, the "old" series should be used again after the Opencast block in the Moodle course has been re-added.

**Screenshots**
![Screen](https://github.com/Opencast-Moodle/moodle-block_opencast/assets/2102425/2aa0fab9-1628-47a6-adc4-7ebd42c82ea9)

If you delete the opencast block again and add it again, another series is created.

** used environment**
- Opencast version: 14.4
- Moodle version: 4.1 with PHP 8.0
- Opencast-Block version: v4.1-r1

**Comment by NinaHerrmann** [comment]
Thank you for reporting! Could you specify if any other behavior led to this? As you said `i.e. remove it from the course page` I was wondering if it is exclusively.

**Comment by mwuttke** [comment]
@NinaHerrmann, in my opinion, there is no other cause for this behavior. In any case, I can't think of any other, nor have I been able to find it in any other context.

**Comment by NinaHerrmann** [comment]
Thank you!
