### ISSUE TITLE
Error "Can't find data record in database table modules."

### ISSUE THREAD

**Issue by elke-hsh** [Opencast-Moodle/moodle-block_opencast#357]
Error "Can't find data record in database table modules." raised when trying to add an lti-activity via `addlti.php` or `addltiepisode.php`.

I fixed it by changing strictness to `IGNORE_MISSING` instead of `MUST_EXIST` in request for module in 
`classes/local/ltimodulemanager.php`.

```php
// Lines 446 - 452
$module = $DB->get_record('modules', ['name' => 'opencast'], '*', IGNORE_MISSING);
if ($module) {
    $defaults = manager::get_default_completion($course, $module);
    foreach ($defaults as $key => $value) {
        $moduleinfo->$key = $value;
    }
}
```

We are not using mod_opencast for the moment, so we are just including series and episodes with lti.

**Comment by justusdieckmann** [comment]
Hey @elke-hsh,

thanks for the post! #361 contains your suggestion.

Cheers
Justus
