### ISSUE TITLE
Subtitles are not displayed in Paella Player 7 when using mod, filter or repository plugin

### ISSUE THREAD

**Issue by mwuttke** [Opencast-Moodle/moodle-block_opencast#367]
In contrast to the LTI integration, subtitles are not displayed when using the mod, filter or repository plugin in Paella Player 7.

Is it possible that the Paella Player 7 in the mod plugin cannot yet handle the conversion of subtitles from attachments to tracks?

**Our setup**
OS: Debian bookworm
Moodle version: 4.1.9+
Opencast version: 15.3
Moodle block plugin for Opencast Version: v4.3-r2

**Comment by ferishili** [comment]
Please follow this issue in this PR: https://github.com/Opencast-Moodle/moodle-mod_opencast/pull/49
