### ISSUE TITLE
Providing single video as an lti module doesn´t work

### ISSUE THREAD

**Issue by jqr86** [Opencast-Moodle/moodle-block_opencast#377]
Hi there,
we have following installation:
Opencast 15.1
Moodle 4.1
block_opencast v4.3-r2
tool_opencast v4.3-r1

Problem:
When providing a single video as an activity for students to watch directly in Moodle, I get following error in Moodle.

![Bildschirmfoto 2024-04-30 um 09 29 17](https://github.com/Opencast-Moodle/moodle-block_opencast/assets/63040266/2a5853da-0870-45ee-a8e3-782b90529eee)

We do not have opencast_mod installed.

But as a test we installed opencast_mod (v4.3-r1) and deactivated it in Moodle and the providing of the single Video worked fine.

This issue is somehow related to: https://github.com/Opencast-Moodle/moodle-block_opencast/pull/361

Greetings Raffaela

**Comment by mwuttke** [comment]
@elke-hsh, please can you make a pull request for this patch?

**Comment by jqr86** [comment]
@elke-hsh, many thanks for the answer. 
I'm sure I didn't make myself clear, but we have installed block_opencast version v4.3-r2 and the above-mentioned patch and we still get the error.

If we adjust the line 446 in classes/local/ltimodulemanager.php like this:

 `446 $module = $DB->get_record('modules', ['name' => 'LTI']);`

so instead of 'opencast' insert 'LTI', it works.
