### ISSUE TITLE
string keys should be in the correct order

### ISSUE THREAD

**Issue by mwuttke** [Opencast-Moodle/moodle-block_opencast#380]
For Moodle 4.4 and the OC-Plugin (version 4.4-r1) the string keys of the language file should be in the correct order (see the [Code prechecks page](https://moodle.org/plugins/block_opencast/v4.4-r1/32301?smurf=html)).

**Comment by bluetom** [comment]
Fixed by a merge. See https://github.com/Opencast-Moodle/moodle-block_opencast/pull/383
