### ISSUE TITLE
[block_opencast v4.4-r1] inconsistency between upgrade.php and versions.php

### ISSUE THREAD

**Issue by mwuttke** [Opencast-Moodle/moodle-block_opencast#381]
There is a versionsstring inconsistency between upgrade.php and versions.php

If you try to upgrade the block_opencast plugin from version v4.3-r2 to v4.4-r1 the new table `block_opencast_importmapping` will not be installed, because of the inconsistency between the savepoint number in the [upgrade.php](https://github.com/Opencast-Moodle/moodle-block_opencast/blob/master/db/upgrade.php#L832) and the version number of the [versions.php](https://github.com/Opencast-Moodle/moodle-block_opencast/blob/master/version.php#L28)

We have tested with Moodle 4.1.11 and the block_opencast version 4.4-r1.

**Comment by NinaHerrmann** [comment]
We could reproduce that. The fastest fix would be to adjust the upgrade.php to insert the table conditionally.

**Comment by mtneug** [comment]
@NinaHerrmann @justusdieckmann: can this be closed?

**Comment by bluetom** [comment]
Has been fixed by a merge. See https://github.com/Opencast-Moodle/moodle-block_opencast/pull/382
