### ISSUE TITLE
Offering workflow configurations when uploading a video

### ISSUE THREAD

**Issue by ferishili** [Opencast-Moodle/moodle-block_opencast#389]
This is a feature request, to offer the upload workflow configuration panel parameters to the lecturers when uploading a video:

### Use case:
Currently, it is not possible for the lecturer to decide which subtitles to add to the uploaded video, unless after the video is uploaded (maybe with hard-coded auto-subtitles in upload workflows) and run a specific workflow (e.g. Whisper English) afterward. This process will take a lot of time, even worst if the video is long it could become a 2 days job!

### Feature Request:
To make it possible to offer workflow configuration panel parameters to the lecturers in order for them to select which auto-subtitle system for which language to use upon uploading the video. This at the end goes to the upload workflow and runs the requested sub-workflows by demand!

**Comment by mtneug** [comment]
+1 for adding support for configuration options for ingest uploads.

But again, this has nothing to do with transcription services. Usually, the Opencast admins will implement one service in their ingest workflow (or allow for it with later workflow execution). And if users already have WebVTT files, they should upload them together with the videos during the same ingest. This means that we cannot use the External API for ingests as this only supports 2 videos and 1 audio track. Instead the Ingest API must be used.

**Comment by mtneug** [comment]
ILIAS approaches this in the following way:

LMS administrators define the available ingest configuration options in the LMS plugin configuration (can be imported automatically from Opencast). They can then decide what options should be presented to the user and what options are not and may have specific values. The last time I heard from ILIAS, it only supported boolean options, but they might have already implemented other types.

**Comment by ferishili** [comment]
Thanks for your explainantion, I was involved in some new implemenetations around this feature in ILIAS.

You mentioned only ingest upload, but it can also be offered for the api upload, since the create event api also accepts processing parameter and we can pass the config panel params to it and run the normal create as well!
It has nothing to do with uploading VTT (subtitle) files or video files upload, it is only a matter of discovering the config panel params, offer the input value to the lecturer and them pass those values to the workflow to use the as for what they intended to do!

**Comment by ferishili** [comment]
As to being notified :D
For those who are interested, the PR is ready and the automated tests are all green!
Please have a look and give your feedbacks to improve the feature!
I hav tried to write a full description in the PR and for those who are willing to test it, a section "Testing" is there as a helper!

BR
