### ISSUE TITLE
Error deleting video

### ISSUE THREAD

**Issue by t-schroeder** [Opencast-Moodle/moodle-block_opencast#39]
Unfortunately I don't remember under which conditions exactly, but the following lines gave me an error when deleting a video:
https://github.com/unirz-tu-ilmenau/moodle-block_opencast/blob/8a62f6b2438ae32042adbf7cd45f8dbd5b497dca/classes/local/apibridge.php#L718-L725

I think we should return inside the `if` block. Because afterwards `$courseid` doesn't have a valid value which means `$series` won't either and the call to `$series->identifier` will fail.

**Comment by synergy-wagner** [comment]
Which line exactely?

**Comment by do-you-even-curl** [comment]
The last line gave an error because `$series` was `null` I think.
