### ISSUE TITLE
Mass action list: All-or-nothing means all-or-nothing - not expected and not ideal

### ISSUE THREAD

**Issue by bluetom** [Opencast-Moodle/moodle-block_opencast#402]
If you have two or more series and want to select all videos of ONE series it is not possible. You can only mark all (or no) event of ALL series.

![image](https://github.com/user-attachments/assets/79a810bc-9c10-45ce-91ab-34e076b20d9e)

**Comment by ferishili** [comment]
You are 100% right.
The (select-all / single) selection of each table has to target only the series (table) that is related to.
Would fix it asap!
