### ISSUE TITLE
Videos not deleted from moodledata

### ISSUE THREAD

**Issue by t-schroeder** [Opencast-Moodle/moodle-block_opencast#44]
After a video has been uploaded it remains in the moodledata folder. Is this intended?

I think this plugin should locally delete the video file once it has been uploaded (or at latest once it has been successfully processed).

**Comment by tobiasreischmann** [comment]
This is acutally done in upload_helper.php:upload_succeeded() (line 196)
There is however one problem. The file is stored as a uploaded files as well as a draft file in the user area. We are deleting only the uploaded file. I investigated deleting the draft file, too. However, there is no good way to do that. The draft file is deleted automatically after some days by the cron.

**Comment by synergy-wagner** [comment]
Hi tobias, 

we do currently a development also on behalf of ETH Zürich to solve this issue. We safely delete user draft files based on source attribute of user draft files and additionally to that we delete files from trash also.

Kind regards
Andi

**Comment by abias** [comment]
Hi @synergy-wagner,

can you tell us if this issue was solved in the meantime and a fix was integrated into this plugin?

Thanks,
Alex

**Comment by abias** [comment]
I think this issue can be closed now.
In recent versions of the block, the video is deleted from Moodledata if the admin enabled the "Delete videofile from moodle" setting of block_opencast.
