### ISSUE TITLE
Add optional configurable help link

### ISSUE THREAD

**Issue by ebbertd** [Opencast-Moodle/moodle-block_opencast#56]
It would be nice to be able to configure a help link that would be displayed for the users trying to use the block.

**Comment by emmanueandales** [comment]
Hi, have used moodle and opencast plugin in a couple of days. I dont have idea how to use this platform and the plugin is nice. But my only concern, if you could provide a better documentation to the plugin. As of now, im having an issue to connect the plugin to the repo opencast. The workflow dropdown not enable to input some parameters. I have already supplied credentials to the opencast API. Would appreciated if you can provide me a simple step by step instructions how to setup the plugin. Thanks

**Comment by abias** [comment]
Daniel, can you please elaborate about this idea?
Where should this help link go to? 
Wouldn't it make sense to add some explanation texts to the overview page of the block if really needed?

**Comment by ebbertd** [comment]
This would lead to some kind of documentation or FAQ where often asked question are answered. Mostly something like: I upload a video but how can I embed it now?
