### ISSUE TITLE
Feature request: Enable instructors to download their videos

### ISSUE THREAD

**Issue by ebbertd** [Opencast-Moodle/moodle-block_opencast#97]
At the moment the instructors can upload and manage their videos / recordings. However, in the case of recordings the instructors often want an export. It would be nice if the instructors could download the videos / recordings directly in Moodle.

This could be either the generate delivery videos or an extra generated export video. Probably admins would want to configure this based on the flavor in the mediapackage in Opencast.

**Comment by taraghi** [comment]
We have received a feature request that allows students to download the videos to watch them offline. The call for this feature request became louder during the COV lockdown period. 

I guess it is still not possible to implement this feature with the current Opencast Moodle plugins, right?

I recommend to generally think about a configurable download option. One idea would be that admins can enable/disable the download function within the block with the following options:

1. only for `editingteacher` => teachers in a Moodle course
2. only for `editingteacher`  and `noneditingteachers` => teachers and tutors in a Moodle course
3. for all course participants (including `students`)
Preferably, a way may be found for teachers to configure themselves whether the download option should be enabled for students.

**Comment by NinaHerrmann** [comment]
Hey @taraghi,
the feature is possible but the Moodle Team in Münster currently lacks the time to implement it (we are even struggling to review pull request).
Feel free to contribute! 
Cheers, 
Nina

**Comment by TamaraGunkel** [comment]
This feature should be integrated with the new activity: Opencast-Moodle/moodle-mod_opencast#5

**Comment by TamaraGunkel** [comment]
Hi,
commit d66e6270c46734e91f7316ce9781d3d6e1f6f046 adds basic download functionality for teachers.
Admins must configure a download channel to which videos are published during the workflow that is executed when uploading a video. There should be only one publication of each video in the channel as there is currently no option to choose from different formats e.g. resolutions per video.
I'll add the possibility for students later as it requires more time to implement.

**Comment by taraghi** [comment]
Hi,
Thanks a lot! We will deploy the feature as soon as it is included in the next official version release :-)
Cheers,
Beni

**Comment by TamaraGunkel** [comment]
Hi,
with the newest release it is possible that teachers can download videos. Contrary to my former comment, multiple download options are offered if more than one media package is included in the publication.
I created a new issue for the student download feature (see #201) because this issue was originally designated to the teacher download which is finished.
